server:
  port: 8882

spring:
  rabbitmq:
    host: localhost
    port: 5672

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

management:
  security:
    enabled: false
